### ISSUE TITLE
Ratio.new/2 with a Decimal numerator and no denominator fails

### ISSUE THREAD

**Issue by kipcole9** [Qqwy/elixir-rational#111] opened 2022-10-08 02:57 UTC
I'm seeing this result on `4.0.0-rc.0` but it may also be in the `3.x` series too. I believe these are expected to work given the documentation but of course please correct me if I have misunderstood.

```elixir
iex> Ratio.new Decimal.new(1)                
** (FunctionClauseError) no function clause matching in Ratio.div/2    
    
    The following arguments were given to Ratio.div/2:
    
        # 1
        Ratio.new(1, 1)
    
        # 2
        1
    
    Attempted function clauses (showing 1 out of 1):
    
        def div(%Ratio{numerator: numerator1, denominator: denominator1}, %Ratio{numerator: numerator2, denominator: denominator2})
    
    (ratio 4.0.0-rc.0) lib/ratio.ex:321: Ratio.div/2
    iex:4: (file)

iex> Ratio.new Decimal.new(1), 1             
** (FunctionClauseError) no function clause matching in Ratio.div/2    
    
    The following arguments were given to Ratio.div/2:
    
        # 1
        Ratio.new(1, 1)
    
        # 2
        1
    
    Attempted function clauses (showing 1 out of 1):
    
        def div(%Ratio{numerator: numerator1, denominator: denominator1}, %Ratio{numerator: numerator2, denominator: denominator2})
    
    (ratio 4.0.0-rc.0) lib/ratio.ex:321: Ratio.div/2
    iex:4: (file)

iex> Ratio.new Decimal.new(1), Decimal.new(1)
Ratio.new(1, 1)
```

**Comment by Qqwy** [comment] 2022-10-15 14:15
This bug only occurs in the new v4 release candidate.
Thank you very much for reporting.

**Comment by Qqwy** [comment] 2022-10-15 14:53
The fix has been merged into the release candidate branch, and release candidate `v4.0.0-rc.1` has been released.

@kipcole9 can you confirm that the problem is solved in the new release candidate?

**Closed** 2023-10-31 03:20 UTC
